dist: trusty
services:
- docker
addons:
- chrome: beta
language: node_js
env:
- TZ=America/New_York
cache: yarn
branches:
  only:
  - develop
  - "/^production\\//"
  - "/^staging\\//"
before_install:
- npm install -g yarn@`jq -r .engines.yarn package.json`
stages:
- name: test
  if: branch !~ /^staging\//
- name: deploy
  if: branch =~ /^(production|staging)\//  AND type IN (push)
jobs:
  include:
  - stage: test
    if: type IN (push)
    install: yarn install --frozen-lockfile
    script: yarn run test
  - if: type IN (pull_request)
    install:
    - gem install travis-artifacts
    - yarn install --frozen-lockfile --ignore-scripts
    - lerna run --stream --since $TRAVIS_PULL_REQUEST_SHA^1 --include-filtered-dependencies
      prepare
    script: yarn run test:since $TRAVIS_PULL_REQUEST_SHA^1
    after_failure:
    - travis-artifacts upload --path services-js/access-boston/screenshots --target-path
      travis/screenshots/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
  - stage: deploy
    install:
    - yarn install --frozen-lockfile --ignore-scripts
    - npx lerna run --stream --scope @cityofboston/deploy-tools --include-filtered-dependencies
      prepare
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: deploy/travis-deploy.sh
      on:
        all_branches: true
notifications:
  slack:
    secure: C2NqstjMXDKohtsPLOuFkGs5xFCuuq4msMeH42XxvdswUMP1eXWadB++gsId8eEg1YcYmJ70o0cG0DUwWBXLOgvlP36WPIo4iXPTGxkdpV+l89llXgX2JrR7l9l7V91ks8njDbkAr0DxIk8P5Mj6koQ8luyQBc0y2yNBJxXcNx6rCEcGOKQpu+gMv6gv76PBzNrZBmY0m+Z/g9RrFfFPVWGQcdSZ2EuX/P3G79mI6I8xdRdvp5+H5NIwFCuBjt/s+1fvi68UxGdllKCihw77fAp06W0CQ47l2xxVIiH3cR80B5vfr8TL3xciT+vD/QhBIOR2Ue9aeVMZNxLF3S+169rwp2Hg5DRrF1H8184xWYOdJcS1SzlTfqiVso4vsUpSQs6aZ7NepD96kuC5nmpcZbqXJsBbSmSbyRfCVQP+NMxJBaeJfxbK66jBGz01PO+F+uZc9Ciwd2aZoo9qv+JobHQYjRT6/rQNyhQOos/W1QUEfPXH4stGWUKf5YQZPKVbLefYiw6d9ThdTndzHntwwwxg9pLFyhSqPOTCDGnP/Gu2v0sTW59FxTenLFnQX9Myo70RZS48nURLbkjxx5/yuPAs2lXwQeJbjpj7EySGZtpBvEcfkFPKnmla1sTDkTU8YnZzg5hQ2Tatt7PzKZxR6vgvmALeOZIDkDvOLUBk2OM=
